application:
  name: Automator

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(funcName)s:%(lineno)d] - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      enabled: true
      level: DEBUG
    file:
      enabled: true
      level: DEBUG
      filename: "logs/application.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

fastapi:
  host: "0.0.0.0"
  port: 5000
  debug: false
  reload: false
  workers: 1
  title: "Automator API"
  description: "Automator Services API"
  version: "1.0.0"
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

database:
  # postgres:
  #   host: "localhost"
  #   port: 5432
  #   database: "automator_db"
  #   username: "user_automator"
  #   password: "p@ssw0rd@Automator"
  #   pool_size: 10
  #   max_overflow: 20
  #   pool_timeout: 30
  #   pool_recycle: 3600
  #   echo: false
  mongodb:
    host: "localhost"
    port: 27017
    database: "automator_db"
    username: "user_automator"
    password: "p@ssw0rd@Automator"
    auth_source: "admin"
    replica_set: ""
    ssl: false
    ssl_cert_reqs: "CERT_NONE"
    max_pool_size: 100
    min_pool_size: 0
    max_idle_time_ms: 0
    connect_timeout_ms: 20000
    server_selection_timeout_ms: 30000
    socket_timeout_ms: 0
    heartbeat_frequency_ms: 10000

security:
  bcrypt_salt_rounds: 12
  password_min_length: 8
  password_max_length: 128
  session_timeout_minutes: 30
  max_login_attempts: 5
  lockout_duration_minutes: 15
  jwt:
    secret_key: "Q2F0Y2hfTWVfSWZfWW91X0Nhbg=="
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
    issuer: "automator-api"
    audience: "automator-users"